trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  versionnumber: $[counter(variables['Build.SourceBranchName'], 1)]

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Towards-AzurePortal'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr repository delete --name demoarc123 --image web-game:$(versionnumber) --yes
      docker build -t demoarc123.azurecr.io/web-game:$(versionnumber) 2048-game
      az acr login -n demoarc123
      docker push demoarc123.azurecr.io/web-game:$(versionnumber)

- powershell: |
    Write-Host "##vso[task.setvariable variable=versionnumber]$($env:versionnumber)"
  displayName: 'Set Version Number'

- script: echo $(versionnumber)
  displayName: 'Print Version Number'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Towards-AzurePortal'
    azureResourceGroup: 'demogroup'
    kubernetesCluster: 'demokubernete'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: false
    configurationType: 'inline'
    inline: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
          name: web-game
      spec:
          replicas: 1
          selector:
              matchLabels:
                  app: web-game
          strategy:
              rollingUpdate:
                  maxSurge: 1
                  maxUnavailable: 1
          minReadySeconds: 5
          template:
              metadata:
                  labels:
                      app: web-game
              spec:
                  nodeSelector:
                      "kubernetes.io/os": linux
                  containers:
                      - name: web-game
                        image: demoarc123.azurecr.io/web-game:$(versionnumber)
                        ports:
                            - containerPort: 80
                        resources:
                            requests:
                                cpu: 250m
                            limits:
                                cpu: 500m
                        imagePullPolicy: Always
      ---
      apiVersion: v1
      kind: Service
      metadata:
          name: web-game
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Towards-AzurePortal'
    azureContainerRegistry: 'demoarc123.azurecr.io'
    forceUpdate: false