trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  versionnumber: $[counter(variables['Build.SourceBranchName'], 1)]

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Towards-AzurePortal'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr repository delete --name demoarc123 --image web-game:$(versionnumber) --yes
      docker build -t demoarc123.azurecr.io/web-game:$(versionnumber) 2048-game
      az acr login -n demoarc123
      docker push demoarc123.azurecr.io/web-game:$(versionnumber)

- powershell: |
    (Get-Content "$(System.DefaultWorkingDirectory)/01_kubernetes_aks/app-deploy.yaml") -replace 'REPLACE_VERSIONNUMBER', '$(versionnumber)' | Set-Content "$(System.DefaultWorkingDirectory)/01_kubernetes_aks/app-deploy.yaml"
  displayName: 'Replace Version Number'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Towards-AzurePortal'
    azureResourceGroup: 'DemoGroup'
    kubernetesCluster: 'demokubernete'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/01_kubernetes_aks/app-deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Towards-AzurePortal'
    azureContainerRegistry: 'demoarc123.azurecr.io'
    forceUpdate: false

- powershell: |
    Write-Host "Version Number: $(versionnumber)"
  displayName: 'Print Version Number'

