trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  versionnumber: $[counter(variables['Build.SourceBranchName'], 1)]

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Towards-AzurePortal'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr repository delete --name demoarc123 --image web-game:$(versionnumber) --yes
      docker build -t demoarc123.azurecr.io/web-game:$(versionnumber) 2048-game
      az acr login -n demoarc123
      docker push demoarc123.azurecr.io/web-game:$(versionnumber)

- powershell: |
    Write-Host "##vso[task.setvariable variable=versionnumber]$($env:versionnumber)"
  displayName: 'Set Version Number'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Towards-AzurePortal'
    azureResourceGroup: 'DemoGroup'
    kubernetesCluster: 'demokubernete'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Towards-AzurePortal'
    azureContainerRegistry: 'demoarc123.azurecr.io'
    forceUpdate: false

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Towards-AzurePortal'
    azureResourceGroup: 'DemoGroup'
    kubernetesCluster: 'demokubernete'
    namespace: 'default'
    command: 'set'
    arguments: 'image deployment/web-game *=demoarc123.azurecr.io/web-game:$(versionnumber)'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Towards-AzurePortal'
    azureContainerRegistry: 'demoarc123.azurecr.io'
    forceUpdate: false