
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Towards-AzurePortal'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.prependpath]$(Build.SourcesDirectory)/path/to/cache/key"
      echo "##vso[task.prependpath]$(Build.SourcesDirectory)/path/to/another/cache/key"
      az acr repository delete --name demoarc123 --image web-game:tag --yes
      docker build -t demoarc123.azurecr.io/web-game:latest 2048-game
      az acr login -n demoarc123
      docker push demoarc123.azurecr.io/web-game:lates

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Towards-AzurePortal'
    azureResourceGroup: 'DemoGroup'
    kubernetesCluster: 'demokubernete'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Towards-AzurePortal'
    azureContainerRegistry: 'demoarc123.azurecr.io'
    forceUpdate: true
